[package]
name = "catenary-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.8.16"
memoffset = "0.9.0"
time = "0.3.29"
rouille = "3.0"
gtfs-rt = "0.4"
reqwest = "0.11"
protobuf = "3.2"
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.28", features = ["full"] }
futures = "0.3"
gtfs-structures = "0.35.0"
tungstenite = "0.20.1"
postgres = "0.19.5"
postgis = "0.9.0"
arguments = "0.7.1"
tokio-postgres = { version = "0.7.8", features = [
    "array-impls",
    "with-geo-types-0_7",
] }
rust_decimal = "1.30.0"
sqlx = { version = "0.6.3", features = ["postgres", "runtime-tokio-rustls"] }
serde_json = "1.0.100"
actix-web = "4.3.1"
regress = "0.6.0"
color-eyre = {version = "0.6.2", features = ["url", "issue-url"]}
fasthash = "0.4.0"
rgb = "0.8.36"
clap = {version = "4.3.21", features = ["derive"]}
itertools = "0.11.0"
fs_extra = "1.3.0"
r2d2 = "0.8.10"
r2d2_postgres = "0.18.1"
bb8-postgres = "0.8.1"
bb8 = "0.8.1"
threadpool = {version = "1.8.1"}
tokio-threadpool = "0.1.18"
qstring = "0.7.2"
rand = "0.8.5"
titlecase = "2.2.1"
rayon = "1.8.0"
chrono = "0.4.31"
geo-types = "0.7.11"
geo-postgis = "0.2.2"
geo = "0.26.0"

[[bin]]
name = "http_server"
path = "src/http-server.rs"

[[bin]]
name = "transitlanddownload"
path = "src/ingest_gtfs_schedule/from-transitland.rs"

[[bin]]
name = "import"
path = "src/ingest_gtfs_schedule/main.rs"

[[bin]]
name = "move_to_prod"
path = "src/ingest_gtfs_schedule/move_to_prod.rs"

[[bin]]
name = "importnopostgres"
path = "src/ingest_gtfs_schedule/nopostgres.rs"

[[bin]]
name = "flattenuncompressed"
path = "src/ingest_gtfs_schedule/flatten.rs"



[features]
#![feature(async_closure)]
