[package]
name = "catenary-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.0"
gtfs-rt = "0.3"
reqwest = "0.11"
protobuf = "3.2"
csv = "1.2"
serde = "1.0"
tokio = {version = "1.28",features = ["full"] }
futures = "0.3"
gtfs-structures = "0.34"

[[bin]]
name = "schedule_ingest"
path = "src/ingest_gtfs_schedule/main.rs"