[package]
name = "catenary-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.0"
gtfs-rt = "0.3"
reqwest = "0.11"
protobuf = "3.2"
csv = "1.2"
serde = "1.0"
tokio = { version = "1.28", features = ["full"] }
futures = "0.3"
gtfs-structures = "0.34"
tungstenite = "0.19.0"
postgres = "0.19.5"
postgis = "0.9.0"
arguments = "0.7.1"
tokio-postgres = { version = "0.7.8", features = [
    "array-impls",
    "with-geo-types-0_7",
] }
rust_decimal = "1.30.0"
sqlx = { version = "0.6.3", features = ["postgres", "runtime-tokio-rustls"] }
serde_json = "1.0.100"

[[bin]]
name = "schedule_ingest"
path = "src/ingest_gtfs_schedule/main.rs"

[[bin]]
name = "http_server"
path = "src/http-server.rs"
