apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment.catenary-backend
  labels: 
    app: catenary-backend
spec:
  template:
    metadata:
      labels:
        app: catenary-backend
      spec:
        containers:
          - name: catenary-backend
            image: localhost/catenary-backend
            ports:
              - containerPort: 5401
            command: ["./catenary-backend"]
            args: ["--postgres",""]
          - name: martin
            image: localhost/martin
            ports:
              - containerPort: 3000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statics-db
spec:
  template:
    metadata:
      labels:
        app: statics-db
    spec:
      containers: 
        - name: statics-db
          image: postgres/16
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Secret
metadata: 
  name: secret.catenary-backend
type: kubernetes.io/basic-auth
stringData:
  username: statics
  password: 
