name: Deploy on Successful Build

on:
  workflow_run:
    workflows: ["Rust"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
        shell: bash

      - name: Setup ssh cloudflared config
        run: |
          mkdir -p ~/.ssh
          printf "Host sshtransit02.kylerchin.com\nProxyCommand /usr/bin/cloudflared access ssh --hostname %%h" > ~/.ssh/config
          echo "${{ secrets.REMOTE_SERVER }}" > ~/.ssh/known_hosts
        shell: bash
        
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        shell: bash

      - name: SSH
        run: |
           ssh lolpro11@sshtransit02.kylerchin.com "cd /home/lolpro11/catenary-backend; git pull; echo "${{ secrets.SUDO_PASSWD }}" | sudo -S -u runner systemctl restart transitbackend.service"
        shell: bash
