name: Deploy on Successful Build

on:
  workflow_run:
    workflows: ["Rust"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
        shell: bash

      - name: Setup ssh cloudflared config
        run: |
          mkdir -p ~/.ssh
          printf "Host shizuoka.kylerchin.com\nProxyCommand /usr/bin/cloudflared access ssh --hostname %%h" > ~/.ssh/config
          echo "${{ secrets.SHIZUOKA_PUBLIC  }}" > ~/.ssh/known_hosts
        shell: bash
        
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        shell: bash

      - name: SSH
        run: |
          ssh catenary_backend@shizuoka.kylerchin.com "cd catenary-backend | cargo build --release | systemctl --user restart transitbackend.service"
        shell: bash
